### ISSUE TITLE
Add default identity key

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#303]
## Motivation

Best practice with SSH connections is to use key based authentication.

## Scope

This issue includes basic support. It Lacks multiple keys, import and more than the ED25519 type.

### New Server

The user adds a gate, keying the address and username. T7 then tries to connect using the default key. If it fails it asks for the password. Once the connection is made the user is presented with a menu:

- Just let me in
- Copy the key
- Never use a key

If the user asks to copy the key he'll be presented with the script we use
to update the keys and a menu:

```
if test ! -e $1; then
   mkdir $1
   chmod 700 $1
fi
if test ! -e "$1/$2"; then
   touch "$1/$2"
   chmod 600 "$1/$2"
fi
echo $3 >> "$1/$2"
```

- Run script
- Copy key to clipboard
- Cancel

Once T7 does as the user commands he connects the gate.

### Adding by proxy

A freelance wants access to an ec2 instance of a client. He opens TWR and types`copy-key`. It gets a messages that the  key was copied to the clipboard. They then switch to slack and posts it in the client's \#devops channel.

## TODO

- [ ] On connect, get the key using `SSH.getOrCreateKey('dev.terminal7.keys.default')`
- [ ] Upgrade SSHSession to try the key
- [ ] Add the copy-key command
- [ ] Develop version 0.3 of the ssh plugin to add support for keys

**Comment by eyal-sasson** [comment]
How should the private keys be stored? In LocalStorage?

**Comment by daonb** [comment]
Right. For improved security, keys can be protected by a passphrase. We can generate a random passphrase and store it as a biometric locked credentials using a [plugin](https://www.npmjs.com/package/capacitor-native-biometric).
But before we can use the plugin we'll have to upgrade capacitor to 4.x which shouldn't be too hard.

At the bottom end, the plugin will pass all the data to  [libssh2_userauth_publickey_frommemory](https://www.libssh2.org/libssh2_userauth_publickey_frommemory.html).

**Comment by eyal-sasson** [comment]
Seems like we need to implement something like `startSessionByKey` in [tuzig/capacitor-ssh-plugin](/tuzig/capacitor-ssh-plugin). Since I'm not that familiar with Swift and also don't have any way to test Swift code, I don't think I can do it.
